GET http://localhost:3000/players/
Content-Type: application/json


####
POST http://localhost:3000/players
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}



####
GET http://localhost:3000/players/:playerId/

Content-Type: application/json
{
  "playerId": 1,
  "playerName": "Lakshman",
  "jerseyNumber": 5,
  "role": "All-rounder"
}
###

PUT http://localhost:3000/players/:playerId/

Content-Type: application/json
{
  "playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}



###

DELETE http://localhost:3000/players/:playerId/